### ISSUE TITLE
Build fails for node .8

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#15]
It fails because it seems `queue-async` and `d3-dsv` are not available in that version of npm?

```
Using worker: worker-linux-docker-7fac1d96.prod.travis-ci.org:travis-linux-2

Build system information
Build language: node_js
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=master git://github.com/mhkeller/indian-ocean.git mhkeller/indian-ocean
Cloning into 'mhkeller/indian-ocean'...
remote: Counting objects: 266, done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 266 (delta 129), reused 207 (delta 74), pack-reused 0
Receiving objects: 100% (266/266), 76.62 KiB | 0 bytes/s, done.
Resolving deltas: 100% (129/129), done.
Checking connectivity... done.
$ cd mhkeller/indian-ocean
$ git checkout -qf 0e872e564ad3304676f09bc41bc9a58f5f04c785

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
$ nvm install 0.8
######################################################################## 100.0%
Now using node v0.8.28
$ node --version
v0.8.28
$ npm --version
1.2.30
$ nvm --version
0.23.3
$ npm install 
npm http GET https://registry.npmjs.org/d3-dsv
npm http GET https://registry.npmjs.org/queue-async
npm http GET https://registry.npmjs.org/shapefile
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/documentation
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/standard
npm http 200 https://registry.npmjs.org/queue-async
npm ERR! Error: No compatible version found: queue-async@'^1.0.7'
npm ERR! Valid install targets:
npm ERR! ["0.0.2","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.8.28/bin/node" "/home/travis/.nvm/v0.8.28/bin/npm" "install"
npm ERR! cwd /home/travis/build/mhkeller/indian-ocean
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm http 200 https://registry.npmjs.org/d3-dsv
npm http 200 https://registry.npmjs.org/documentation
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/chai
npm http 200 https://registry.npmjs.org/mocha
npm http 200 https://registry.npmjs.org/standard
npm http 200 https://registry.npmjs.org/shapefile
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/mhkeller/indian-ocean/npm-debug.log
npm ERR! not ok code 0

The command "eval npm install " failed. Retrying, 2 of 3.

npm ERR! Error: No compatible version found: queue-async@'^1.0.7'
npm ERR! Valid install targets:
npm ERR! ["0.0.2","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.8.28/bin/node" "/home/travis/.nvm/v0.8.28/bin/npm" "install"
npm ERR! cwd /home/travis/build/mhkeller/indian-ocean
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/mhkeller/indian-ocean/npm-debug.log
npm ERR! not ok code 0

The command "eval npm install " failed. Retrying, 3 of 3.

npm ERR! Error: No compatible version found: d3-dsv@'^0.1.5'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.5"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.8.28/bin/node" "/home/travis/.nvm/v0.8.28/bin/npm" "install"
npm ERR! cwd /home/travis/build/mhkeller/indian-ocean
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/mhkeller/indian-ocean/npm-debug.log
npm ERR! not ok code 0

The command "eval npm install " failed 3 times.


The command "npm install " failed and exited with 1 during .

Your build has been stopped.

```

**Comment by ebrelsford** [comment]
That makes sense, let's just disable travis for that version of node. It was a complete guess on my part.

**Comment by ebrelsford** [comment]
Done in 2e0558bd

**Comment by mhkeller** [comment]
👍
